repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
    
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.6
    hooks:
      - id: golangci-lint
        entry: golangci-lint run --fix
        language: golang